### ISSUE TITLE
Not signed in.

### ISSUE THREAD

**Issue by gonssalu** [lin-e/Skype4Sharp#14]
About 2 weeks ago I used Skype4Sharp and it worked now it has been giving me this error: An unhandled exception of type 'Skype4Sharp.Exceptions.InvalidSkypeActionException' occurred in Skype4Sharp.dll
Addditional information: Not signed in

I know it is because skype changed the authorization method.
I'm justasking if anyone knows any solution to this? Or if there will be any kind of update on Skype4Sharp to fix this?? Thanks.

**Comment by euronull** [comment]
I was looking a solution but.. without any result.
For me: I migrate my bot to https://docs.botframework.com/en-us/skype/getting-started cuz Microsoft is gonna close it's rest api. It's not so hard. You can use https://docs.botframework.com/en-us/csharp/builder/sdkreference/

**Comment by itsGhost** [comment]
lollll
