### ISSUE TITLE
Any solution to Skype login? (other then use their Bot Framework)

### ISSUE THREAD

**Issue by d-kar** [lin-e/Skype4Sharp#15]
Yesterday login to skype through this framework stopped completely. What are the alrenatives to MS Bot framework?

**Comment by knackrack615** [comment]
Nothing, my suggesting would be to move off Skype completely

**Comment by ducc** [comment]
(try making discord bots)

**Comment by 10der** [comment]
after quick investigation:
1) use new endpoint public const string MainDomain = "client-s.gateway.messenger.live.com";
2) if put cookies into private string getSkypeToken() like
```
            string temp = "mkt=en-US;MSFPC=ID=e03edbe7c0554ed9a5c220861515d03b&CS=3&LV=201701&V=1;wl_optintopcexperienc [skipped]";
            string[] cookies = temp.Split(';');
            foreach (string cookie in cookies)
                parentSkype.mainFactory.mainContainer.SetCookies(new Uri("https://" + WebRequestFactory.MainDomain), cookie);
``` we are still can able to login! 
simple loging via https://secure.skype.com/ and grab browser cookies
3) diable all methods with api.skype.com - I don't know how to pass authentication for this domain!

**Comment by d-kar** [comment]
10der, did you fix the issue? Mind creating pull request? Thanks!

**Comment by d-kar** [comment]
Actually, the fix was already there, just need to switch to use MSNP24 type token and proper result handling, will create pull request
