### ISSUE TITLE
Poller fails to check api and program crashes

### ISSUE THREAD

**Issue by Tehtafara0** [lin-e/Skype4Sharp#4]
Sometimes the poller cannot check the API and the program crashes even it has try everywhere.

**Comment by lin-e** [comment]
How long would the API be running, for it to reach that point?

**Comment by Tehtafara0** [comment]
20-30 minutes. I putted TRY everywhere in Poller.cs and i no longer have problems.

**Comment by lin-e** [comment]
Put what everywhere?

**Comment by knackrack615** [comment]
Hes trying to say that he surrounded everything with try statements in poller.cs

**Comment by lin-e** [comment]
Well, duh. Obviously that will 'fix' crashes. I'll check out what the actual exception is, but I'll make it log to console if there are any errors.

**Comment by itsGhost** [comment]
Reopened; try/catch is a placebo solution. Other apis have been having this same issue and is worth investigating.

**Comment by lin-e** [comment]
Depends on the HTTP error code, one could be just Skype's side messing up, the other would be the session expiring. Don't really have time to work on the API as of now.

**Comment by itsGhost** [comment]
Skype? Mess up? never

**Comment by itsGhost** [comment]
Deprecated issue. Skype's fugly gateway is better now-ish
