### ISSUE TITLE
Nuget?

### ISSUE THREAD

**Issue by ghost** [lin-e/Skype4Sharp#5]
Hi, is this library available on nuget?

**Comment by lin-e** [comment]
No, mainly because I don't know how to. xD

**Comment by ghost** [comment]
I'm sure it would not be hard

https://www.nuget.org/users/account/LogOn?ReturnUrl=%2Fpackages%2Fupload

**Comment by itsGhost** [comment]
Probably not going to happen since the donald is busy trying to get elected and stuff. Just add it as a refrence for now.
