### ISSUE TITLE
Possibility of sending files

### ISSUE THREAD

**Issue by ACXap** [lin-e/Skype4Sharp#8]
Do you have plans to realize the possibility of sending files?

**P.S. Thanks a lot for your great job.**

**Comment by lin-e** [comment]
I'll look into it when I have time. Doing my GCSEs in the following two months.

**Comment by itsGhost** [comment]
> implies GCSEs are hard

**Comment by ACXap** [comment]
I Tried:
[SendImage.txt](https://github.com/lin-e/Skype4Sharp/files/254020/SendImage.txt)
It works for me

**Comment by lin-e** [comment]
I already have sending image code, on another project. Image sending and file sending are different on Web Skype's end (if I remember correctly)

**Comment by ACXap** [comment]
Really different, but only slightly. The sequence of actions is the same, we get the file name (the path to save), and then send the file with a link.

**Comment by itsGhost** [comment]
Really different but fuck off.

**Comment by itsGhost** [comment]
@lin-e ye, the endpoints for uploading (extracted from the regular skype client, if you still use that code you got from me) are the same, however, _its only the post message payload that is different, otherwise, everything is exactly the same.

**Comment by ACXap** [comment]
and you can download your example?
[SendFile.txt](https://github.com/lin-e/Skype4Sharp/files/257437/SendFile.txt)

**Comment by itsGhost** [comment]
> and you can download your example?

wat
